language: java
sudo: true
addons:
  ssh_known_hosts: domek.xyz
services:
- docker
- postgresql
jdk: oraclejdk8
before_script:
- psql -c "create database pik_shop_test;" -U postgres
- psql -c "create user pik_shop_test with password 'pik_shop';" -U postgres
- psql -c "grant all privileges on database pik_shop_test to pik_shop_test;" -U postgres
script: "./scripts/run_build"
deploy:
  provider: script
  skip_cleanup: true
  script: "./scripts/run_deploy"
  on:
    branch: production
env:
  global:
  - secure: CVY623yjdgZhYntxXafl0LPjG/TvkMEpMLeuYf/snS5Un7NUYJXL4tKODRjNEW8UmVMkW7Euwbtm13i2q8nX0B15MywgEc4luqlMIgt7gKPEAXRS7UFAITXrEXYfJsndMrTstDgW4vV4q+oNt3hnJ4jbt7qKiTAK3l5T6Hx+aNbNS6i7UeYPUlBRGeFCSnThXFfXbo36R8Z5zNocjXJju5VKh/+yWiNzpQC+WHQR1NFV5zlod32phUwG7SqNndFbS5jIpLpMDPsdT5XAGS7U5tmCTOmdlAragM/iK4qD5cgM32eXdmnJ64+QHzSb7Bc+eWO9pYr6eDIVSEY2tlSu81Ryb0MSIfLUQQ+lx/yt+fM2tDgcolBftlHQqGDhni+2h39cvhaPbHTpXEoMeqBtos8NILg095k0AD0307aAWWWbeVuZ2s+8NBeTYe6CAn9Dqt51UHr/Rjre7iKFH82UlQftaoOIUIOR9uA8FlGpYGIuGuGcJB/cYmJJ1orhugfsILSLF9ZvwEN9Dd/NODneNzKaNIjC/v+6yAfzvpzh/ZlxqSkLMVjuEDL/3OpbTzrEKezdJVlVDyoUsjEkCs+BuluUmyjFpaJNhfdslH5e5c8Y3apdow+Id+OWKRGmpZBFb7mMnC6vZk7alEkhbsBFrF54EnbI2I/FuUmvb23c6fs=
  - secure: d/RWbvTO7q+vpQaWQiQRn7ysNa0+f69lqD3lK743pikfvh00A/nXM3sVpDT6kIKfDTd79vJ+hvy+zXuGIEJDgv/D1E5+P1BuJ0cp/R/iknbqD72mEXK8rdqnveIbrSsSxAUCpI/vWUYWqYYX8dc/Cw3ZI3k/zTAoIDa9AeJjXLoucKyd7FqUIJTsAgf1mOrAEBrOdKk2oTigRjPng30EcUlIxrL3efYD0jD8AT0mb0YWjR6PtSpnkiSP98p6d9TmVD/k0qzMbpHVgk7XIMxAVmyUbCujVqtjA0aTiNLMtRDQvndBIaygDx1LgsRMIspK0nkUHFEh+1SEyiW4DQCAvyyBjWhpMzdd+JdtUB1rAMLpjh3v1Rzh9zIBtxddRM8JTrDEX1//88r6NfR6Y0mKG2DJ+W18LIDoJjsSFEnKLGP5z6YLpdgxsJWjpkq72qS5zCtFav65BFmE/7+Y3u1ak3CprHwlYTozwmuSiu0Bdrf1NcQxMTVRm8pPEC0p98K8ekd/hwFODLA7Z9M7dVxtkGpYlt31iVXuls/EssXU0jCvx7jaEcB8wxV2PzUJ95ZtToHR2nXh1XLFwqmgF+6jzRR26lV4Hi9COPJoyZtngXnomRalzjI95RbJotaY0Mn8SgfRlPRjI9Bnwc60lu8Y92xlAIEgZCU98ust67RDn4Q=
  - secure: lED5RwRH1r/Uiv17T6luKyFP31AnPrPtagaPEDhQ2GijppQYZSvBBCrs7tjhHx9/kMw7X8Rqhw43rBEB4y7U5xR0PiPQJ8cq1g/GUO/KV5fKy3dzDuFVN2jVSbxAFH4NiPvoKzQWrNAdNDtNL1J0QupHmuixToWj7ygM2IRWBF+SqULMVxrRzLKvhtHMi2zcQGU+ghmViNymlYM0FNBJBpO3cmCRANaBGGMggPyarIithbupAyG5+/dQyw9ADcmAl0FdL6VAYDJ2VCheBIAZOp0haeVyhlUwdOsXmMS1znnZybaR7ncFfXRjU//A164FIS8y2F8kzzMXyKD375Iy+KcQfrMLjCYWzUlg6z+ePBh4rge8JjEejO+mzcdL8IndiurOmFvbc7FzuVisZmoJSWhHYKxy643vRJfGfctewBiriTwQBZMmeCdITlg5lZ4xSDkHLTgydeCRjwfGgmbeVxnM1pWk9xSCemS9xpHAvNYoio92qHarU4uxUHABzyLDt/F9T8Z044oWioLlzw02o/d/IXj4C75qRJvGVmmWCc4aviP9FLIqfZUA4dUqDnA94pDDcGged84to/onnbt2o0Y2F8cKARDXdgURtileWe4NPSMa+gJODnbLBWa5pxzkLwsWBIk0+vppM25gc7aU65wU4Hhal7bR3+7ScfOgpBg=
  - secure: YWLt6uHDWrvpsWrWxUSMdKhLdbyKsjmyHxvf7WZO0KjhmjCmKrOGj3micgm9Qv2pZBCMe4/hcAFqbuzkUJmtD/qSlEEK4eKL5oKz+8WKmk9wlHCzW9W5oznzsZMjEjIM0YaCcgSrtZXFNdZ/MBAyEBWwtQo2BaSQqr3GPFX1i5IJjtVfrLPnW4QA94eCZHEvS5r6Wip+oy57JeZr95Er2/sp7pCunQ3MsF2WC23bZwqI4HqoCXn/pLwis2bHobR2XBaWOVtC2dv4r3XdUPE6iQkrXoWUSzbt0/gUz8rq/yMWm/t7nru3/rxsmi74e1YFTw/mpWXaJdPJrhdZZVTvNFpy0k8t0vdteSRoGUrWn1OXVYDg4VO2OSBqz841/HJIB57Kyc5kDvkOoZv9LXp0BOEhXo5KpEy30edXs0NXobV5t/OpuEMXzNCwJhLKQXWYpJuSugnJv6334k2MM6z/PsPHeTdynRNq+R6Nfz0fu4nKCLZQ1GdXVtNX2Y4xO+6OToU4IaFR6/ihN7e3s0JqyHbel7rGGtSvh7pWU4hpl0j9f7br87O1PjAuTst4zfrTlKBRU5JQrONXw9PXaUSRMuDD5ys77CQB/2eBfga+xLSxS4EfphBHf4C562brannXQh3iai79OqgvMZHUjLZlTFjaPDa9KYOLIpqOCy8FrJc=
before_install:
- openssl aes-256-cbc -K $encrypted_be31fdac465d_key -iv $encrypted_be31fdac465d_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
