language: java
sudo: true
services:
    - docker
    - postgresql
jdk: oraclejdk8
before_script:
    - psql -c "create database pik_shop_test;" -U postgres
    - psql -c "create user pik_shop_test with password 'pik_shop';" -U postgres
    - psql -c "grant all privileges on database pik_shop_test to pik_shop_test;" -U postgres
script: ./scripts/run_build
